# Generated by Django 4.0.1 on 2022-01-22 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(default='', max_length=70)),
                ('profile', models.TextField(default='', max_length=500)),
                ('loan_acc_no', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Excel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('add_1', models.CharField(default='', max_length=50)),
                ('add_2', models.CharField(default='', max_length=50)),
                ('add_3', models.CharField(default='', max_length=70)),
                ('off_code', models.IntegerField(default='')),
                ('landmark', models.CharField(default='', max_length=70)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('agr_date', models.DateField()),
                ('lrn', models.IntegerField(default='')),
                ('tenor', models.DateField()),
                ('adv_emi', models.IntegerField(default='')),
                ('mob', models.IntegerField(default='')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('add_1', models.CharField(default='', max_length=50)),
                ('add_2', models.CharField(default='', max_length=50)),
                ('add_3', models.CharField(default='', max_length=70)),
                ('home_code', models.IntegerField(default='')),
                ('landmark', models.CharField(default='', max_length=70)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zone_name', models.CharField(max_length=50)),
                ('region_name', models.CharField(max_length=50)),
                ('branch_name', models.CharField(default='', max_length=70)),
                ('branch_code', models.IntegerField(default='')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
        ),
    ]
